# Generated by Django 4.2.5 on 2023-09-24 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_variation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='variation',
            name='variation_category',
            field=models.CharField(choices=[('event', 'event')], max_length=100),
        ),
    ]
