# Generated by Django 4.2.5 on 2023-09-24 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_alter_product_coach'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='coach',
        ),
        migrations.AddField(
            model_name='product',
            name='stock',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
