# Generated by Django 4.2.5 on 2023-09-24 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_remove_product_coach_product_stock'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='stock',
        ),
        migrations.AddField(
            model_name='product',
            name='coach',
            field=models.TextField(blank=True, default='Generic', max_length=500),
        ),
    ]
