# Generated by Django 4.2.5 on 2023-09-24 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_remove_product_stock_product_coach'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='level',
            field=models.CharField(choices=[('1', 'Level 1'), ('2', 'Level II'), ('3', 'Level III')], default='1', max_length=255),
        ),
    ]
