# Generated by Django 4.2.5 on 2023-09-24 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0009_product_level'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='coach',
            field=models.CharField(blank=True, default='Generic', max_length=500),
        ),
    ]
