# Generated by Django 4.2.5 on 2023-10-07 13:29

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0012_alter_product_description'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='description',
            new_name='longdescription',
        ),
        migrations.AddField(
            model_name='product',
            name='shortdescription',
            field=ckeditor.fields.RichTextField(default='Default Short Description'),
            preserve_default=False,
        ),
    ]
