# Generated by Django 4.2.5 on 2023-10-24 03:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0015_product_pdf_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='weeks',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
