# Generated by Django 4.2.5 on 2023-11-26 07:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('store', '0018_downloadrecord'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='coach',
            field=models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.coach'),
        ),
    ]
