# Generated by Django 4.2.5 on 2023-10-01 11:37

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='timings',
            new_name='timingsinMinutes',
        ),
        migrations.AddField(
            model_name='order',
            name='timingsinSeconds',
            field=models.IntegerField(default=2, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(59)]),
            preserve_default=False,
        ),
    ]
